---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: appsecret
  namespace: default
spec:
  encryptedData:
    apikey: AgAzfj9hoKeLsao8MOHt02PzHmsj8LoGp7Q6RUTC8sMZ+kivYui42DmW+zH4QuA2mPo8pFbD34Ov0aB1ykfBxi2ycB4gLZrVSD9Fn88e85CB3UPcre1gIjVSPRJgtMSib98Wak9tS5qLFUa0FVcMwAoil/0bmn70/U6jgPfvA0Wy2NbEsJXmfndMQngOj+jgExuD6Iam3p0ZobqNilCNJrAVs82AMdxUOJaoQSO2fkXNSfc72fwwUeATcuMZEZwF6UZvIq5+N3+qzfkrq6/hBUao6bK8QGdkKZ0nblMxphD452MwDNwLWzNX5cDfJlgSCj4eUhAY0pUSIEmstabjzq6VwblYnq8f65pJ8+jFbohXwcfqyJj0ujUsj+GfDyGNIUUsbWwU6zC99O7tzKm0VA27XmpItrXuuiKAqpBh4xNdAahMExOuImqMgxmLmnZw0xpJaAjYTHnD9VlcXSWpB8OxicZZg3ifSO9lOTPRlLev4g9ahrSqROjpW299yX+kUTYPljaviMPXA2l8mjAxgB3BnUWqDY8lbGD0Wuq1fXB7dTOfJSjSX8bWcWYomk53ajGCW6kKNTlr49zC1xCxzbc/CVu+zKrkBSzszk+v4h7JS8lhNhSmApatMASaj+XUQ40iJd81PIPtV/SZujVqAFWviu7itWAbpGeYIIJLk5fqxnS7Caq9i45UzMjr26lRfQKqH/40OrveSIhi5QmbQm6gH1a1H95dKbnM1aONW69Nrjy9v+WLSjI=
  template:
    metadata:
      creationTimestamp: null
      name: appsecret
      namespace: default
    type: Opaque
